# The Docker image that will be used to build your app
image: jetbrains/writerside-builder:242.21870
# Functions that should be executed before the build script is run
before_script:
  - rm -rf artifacts
pages:
  script:
    - /opt/builder/bin/idea.sh helpbuilderinspect --source-dir . --product Writerside/cnw --output-dir artifacts/
    - python3 -m zipfile -e artifacts/webHelpCNW2-all.zip public
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
    expire_in: never
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
