pages:
  image: node:20.18.0-bookworm
  variables:
    GIT_STRATEGY: clone
    TZ: Asia/Shanghai
    GITLAB_HOST: $GITLAB_HOST
    GITLAB_TOKEN: $GITLAB_TOKEN
    GITLAB_USER: $GITLAB_USER
  script:
    - ./scripts/ci_build.sh
    - ./scripts/push_to_pages.sh
    - mv build public
  artifacts:
    paths:
      - public
    expire_in: 1 week
