pages:
  image: node:20.18.0-bookworm
  variables:
    GIT_STRATEGY: clone
    TZ: Asia/Shanghai
  script:
    - ./scripts/ci_build.sh
    - mv build public
  artifacts:
    paths:
      - public
    expire_in: 1 week
